### ISSUE TITLE
Downloading Embedded Images

### ISSUE THREAD

**Issue by woosal1337** [jeremyephron/simplegmail#29]
I have noticed that even though ```message.attachments``` helps you out to get all the attached image, or whatever it is to the given path/directory, unfortunately, if the image or the file that is sent is embedded, such as it exists in the mail, however, is not attached rather embedded to the sent message, then neither the downloading the mail as using ```message.attachments```, nor ```message in messages``` works. Is there any solution for this feature? Maybe the image link opening, which actually automatically downloads the sent image/file can also be integrated. 

Any suggestions?

**Comment by jeremyephron** [comment]
@woosal1337, embedded images are just elements in the html of the message, they aren't actually included in the email, so you can manually parse the HTML in order to get their source URLs. Here is one example of how to do that using [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/).

```python3
from bs4 import BeautifulSoup

msg = # your message containing embedded images retrieved using simplegmail

# Parse the HTML of the message
soup = BeautifulSoup(msg.html, 'html.parser')

# Find all img tags
imgs = soup.find_all('img')

# Get all the source URLs
urls = [img['src'] for img in imgs]
```

If you want to download and save these images, you can use requests:
```python3
import requests

for url in urls:
    res = requests.get(url)
    filename = # whatever you want to save the images as
    open(filename, 'wb').write(res.content)
```

[This stackoverflow post](https://stackoverflow.com/questions/18408307/how-to-extract-and-download-all-images-from-a-website-using-beautifulsoup) can help you if you want more info.

**Comment by jeremyephron** [comment]
Just to clarify: this kind of feature is beyond the scope of what I believe belongs in the package (because users should handle html parsing of their own emails), but I will add a section to the Wiki with an example like this for others who want to do the same.

**Comment by woosal1337** [comment]
Great, glad to hear that, Jeremy.
