### ISSUE TITLE
Second Gmail Account

### ISSUE THREAD

**Issue by cod3r-dev** [jeremyephron/simplegmail#31]
There is any way to add second account??

**Comment by jeremyephron** [comment]
Yes, go through the process of downloading the client secret file for each account, say they are named `client_secret1.json` and `client_secret2.json`. Then when you make a `Gmail` object for each, you need to pass in distinct values for the name of the credentials file (named `gmail_token.json` by default):

```python3
from simplegmail import Gmail

gmail_acct1 = Gmail(client_secret_file="client_secret1.json", creds_file="gmail_token1.json")
gmail_acct2 = Gmail(client_secret_file="client_secret2.json", creds_file="gmail_token2.json")
```

Just make sure you always use the same file names for the same accounts the next time you run it (otherwise it will ask you to authenticate again if it can't find the `creds_file` specified).
