### ISSUE TITLE
Can't download attachment files when passing filepath

### ISSUE THREAD

**Issue by BisratGetnet** [jeremyephron/simplegmail#34]
File "C:\Users\BisreG\AppData\Local\Programs\Python\Python39\lib\site-packages\simplegmail\attachment.py", line 106, in save
    with open(filepath, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'D:\\Doc\\bndf'

it works with no argument but cant save on other folders

**Comment by jeremyephron** [comment]
@BisratGetnet Will look into whether this is something on simplegmail's end or you may just lack permission to write to that location.

**Comment by jeremyephron** [comment]
@BisratGetnet I think I know what the issue is. If `D:\Doc\bndf` is a *directory* then that would cause the issue. The `filepath` you pass in is not the directory to save it to, but the full filepath including the filename itself. If you want to take the name of the attachment, it can be retrieved from `attachment.filename`.

So you might write the desired code like this:

```python3
import os

# get attachment...

DIRPATH = 'D:\\Doc\\bndf'
attachment.save(os.path.join(DIRPATH, attachment.filename))
```

**Comment by BisratGetnet** [comment]
Thanks a lot!!!!!!! That Helps me,
