### ISSUE TITLE
Downloading multiple attachments consecutively

### ISSUE THREAD

**Issue by mkimura1971** [jeremyephron/simplegmail#40]
Hi. 

I modified the "Downloading attachments" example to loop over messages to download multiple attachments consecutively. My Gmail inbox has 50+ messages and each has one video file (3MB). It starts nicely, but after 20-30 downloads, it stops. It stops at

res = self._service.users().messages().attachments().get(userId=self.user_id, messageId=self.msg_id, id=self.id).execute()

in attachment.py. I left it running for over 30 minutes, but it's simply stuck there. I used signal.larm to force it to time out, but the immediate next attempt gets the same (non) response. If I restart the entire script, it runs fine for a while again.

Any idea how to solve it? Thanks in advance!

**Comment by jeremyephron** [comment]
@mkimura1971 I believe the issue may be hidden by however you modified it to download "consecutively". I just tested the example as is with 100 messages each with a 6MB video file, no issues.

The download is not trivially parallelizable. This has to do with complications of the underlying Google API resource object that is used to make API requests. Are you calling `download()` or `save()` in parallel? If not can you post the relevant code?

**Comment by mkimura1971** [comment]
Thanks for the quick response! My code is essentially this (I simplified the original, but confirmed that this simplified version gives me the same symptom):

from simplegmail import Gmail
import os

gmail = Gmail()
messages = gmail.get_messages(query='in:inbox from:(some@email.net) has:attachment')

for message in messages:
    if message.attachments:
        for attm in message.attachments:
            file_path = os.path.join("data", attm.filename)
            print('File: ' + file_path)
            attm.save(file_path)

**Comment by jeremyephron** [comment]
Does it always stall on the same file?

**Comment by mkimura1971** [comment]
No, it's different each time.

**Comment by jeremyephron** [comment]
I'm not able to reproduce the stalling on my end no matter how many messages or attachments I download, so I'm at a bit of an impasse. If you were hitting google API quotas, it wouldn't stall. My best guess is that it may have to do with your network, since not receiving a response is the most likely explanation for it stalling. If you have access to another network (or can run this on a remote machine with a different connection) that would be one way of testing this.

Otherwise, I recommend you write the script to only process a smaller amount of messages at a time, if you are saying that it consistently doesn't stall for the first X amount of messages.

**Comment by mkimura1971** [comment]
Yes, I'm going to try it from a different network and perhaps a different Google account. Thanks!
