### ISSUE TITLE
Oauth2 doesn't finish the authorization

### ISSUE THREAD

**Issue by eburkland** [jeremyephron/simplegmail#91]
So I'm running your simple send an email message example.  When I test it provides a URL which I open in a browser.  It goes through the "This app isn't verified" prompts.  Then I just get in return something like this 
http://localhost:8080/?code=4/0AVHEtk6kb1g9-ONG_fpT3bLDw3iYslEJO-KY9h_39po8OF8reXlmkCQn_EfPe7M4nNV64g&scope=https://www.googleapis.com/auth/gmail.settings.basic%20https://www.googleapis.com/auth/gmail.modify  
with a blank screen

It just seems that the authorization code isn't making it's way back.
I know there is this --noauth_local_webserver  business but I couldn't for the life of me make that work either
I appreciate your help

**Comment by jeremyephron** [comment]
This sounds like it's more likely an issue with the setup of the app on the google cloud console rather than something related to the library. I haven't encountered this failure mode before. Typically when you get to the URL you posted, you should see something like "The authentication flow has completed" (or potentially a custom page/redirect can be set up in the application), and the application should continue following the `Gmail()` construction.

**Comment by eburkland** [comment]
Thank you for the reply.   As a test I changed gmail.py line 70 noauth_local_webserver: bool = False  to True.
I then received a screen which had me copy an authorization code.  The program then prompted for the authorization code.  I agree that something in the setup isn't correct.  Maybe the callback URL.  I'll keep plugging away.   Again thank you for your time
